### ISSUE TITLE
Issue with compressed resource forks

### ISSUE THREAD

**Issue by erichelgeson** [dgelessus/python-rsrcfork#10]
Hi! I'm trying to extract some resource forks from the file below through the CLI or code, both throw an error when trying to access them - first the CLI - using `raw-decompress`
```
$ unar SCSI_Director_Pro_4.0.sit # https://macintoshgarden.org/apps/scsi-director-pro-40
SCSI_Director_Pro_4.0.sit: StuffIt
  SCSI Director™ Pro 4.0  (370098 B, rsrc)... OK.
Successfully extracted to "./SCSI Director™ Pro 4.0".
$ rsrcfork raw-decompress SCSI\ Director™\ Pro\ 4.0 decompressed-forks.rsrc
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rsrcfork/compress/common.py", line 42, in parse_stream
    signature, header_length, compression_type, decompressed_length, remainder = STRUCT_COMPRESSED_HEADER.unpack(stream.read(STRUCT_COMPRESSED_HEADER.size))
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 18 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rsrcfork", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rsrcfork/__main__.py", line 829, in main
    do_raw_decompress(ns)
  File "/usr/local/lib/python3.11/site-packages/rsrcfork/__main__.py", line 623, in do_raw_decompress
    header_info = compress.CompressedHeaderInfo.parse_stream(in_stream)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rsrcfork/compress/common.py", line 44, in parse_stream
    raise DecompressError("Invalid header")
rsrcfork.compress.common.DecompressError: Invalid header
$ rsrcfork --version
1.8.0
$ unar -v
v1.10.7
$ python3 --version
Python 3.11.2
# macOS 13.1 (22C65)
```

Second in code - accessing it via the python api
```
main.py 
scratch/SCSI_Director_Pro_4.0.sit: StuffIt
  SCSI Director™ Pro 4.0  (370098 B, rsrc)... OK.
Successfully extracted to "scratch/output/SCSI Director™ Pro 4.0".

scratch/output/SCSI Director™ Pro 4.0
Traceback (most recent call last):
  File ".../venv/lib/python3.11/site-packages/rsrcfork/api.py", line 192, in compressed_info
    return self._compressed_info
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Resource' object has no attribute '_compressed_info'. Did you mean: 'compressed_info'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 113, in <module>
    test()
  File "main.py", line 72, in test
    print(f"type: {res_type} id: {res_id} data: {rf[res_type][res_id].data}")
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/rsrcfork/api.py", line 227, in data
    if self.compressed_info is not None:
       ^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/rsrcfork/api.py", line 194, in compressed_info
    self._compressed_info = compress.common.CompressedHeaderInfo.parse(self.data_raw)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/rsrcfork/compress/common.py", line 66, in parse
    return cls.parse_stream(io.BytesIO(data))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/rsrcfork/compress/common.py", line 48, in parse_stream
    raise DecompressError(f"Unsupported header length: 0x{header_length:>04x}, expected 0x12")
rsrcfork.compress.common.DecompressError: Unsupported header length: 0x0000, expected 0x12

Process finished with exit code 1
```

Any help appreciated, thanks for the awesome library.

**Comment by dgelessus** [comment]
Hi, happy to hear that you find it useful :)

The command-line interface is perhaps a bit confusing here. The `rsrcfork raw-decompress` command is probably not what you're looking for - that command is for decompressing *standalone* compressed resource data, outside of a resource fork. For compressed resources *inside* a resource fork (i. e. the usual case), you can use the regular commands (`rsrcfork list`, `rsrcfork read`) and APIs (`rsrcfork.ResourceFile`). The library automatically decompresses the compressed resources, unless you explicitly turn off decompression.

The actual problem here is that the file you linked uses a custom third-party resource compression method. My library doesn't execute `'dcmp'` resources like real Mac OS would - instead, I reimplemented the decompression code from scratch in Python. I've only implemented Apple's three original compression methods from System 7 though. Any other compression methods simply don't work with this library.

You might want to try [resource_dasm](https://github.com/fuzziqersoftware/resource_dasm) instead - it also supports resource compression and *can* execute custom decompressors. The README explicitly mentions "Ben Mickaelian's self-modifying dcmp 128", which seems to be what your file uses.

**Comment by dgelessus** [comment]
I also pushed a small fix to the code that parses the compressed resource header. This custom compressor puts a slightly odd value in one of the header fields, which my code failed to parse before. Now if you run e. g. `rsrcfork list` on the file, it will at least show the uncompressed sizes correctly, even though it can't actually decompress the data.

**Comment by erichelgeson** [comment]
Awesome, thanks for the info I'll take a look at that project! It seems there could be any number of `dcmp` methods. My use case is to go through a lot of files to grab their resources - so I may have to detect unknown `dcmp`'s and drop them into an emulator and have a little c++ program dump the resource forks.

Leaving this here for future people to stumble across. http://preserve.mactech.com/articles/mactech/Vol.09/09.01/ResCompression/index.html

**Comment by dgelessus** [comment]
Yeah, since the `'dcmp'` resources are just 68k machine code, there are probably lots of obscure ones out there. From what I've seen, there are some common third-party decompressors that could be reimplemented like the Apple ones, but to really support *all* possible compression methods, you have to emulate the `'dcmp'`s like resource_dasm does.

> Leaving this here for future people to stumble across. http://preserve.mactech.com/articles/mactech/Vol.09/09.01/ResCompression/index.html

I also collected some links when I went down this rabbit hole a few years ago. Many of them are well-known, but perhaps you'll find something useful there: https://github.com/dgelessus/mac_file_format_docs

Unfortunately, the whole `'dcmp'` machinery seems to be completely undocumented, beyond the bits explained in the MacTech article. (Fun fact: the website of the company mentioned in that article is somehow still up: http://www.alysis.us/arctechnology.htm)

**Comment by dgelessus** [comment]
Ah, I see this became https://resourceforks.com/ in the end? Neat :)

Closing as the original bug should be fixed now. I *might* implement more decompressors in the future, but realistically that won't happen anytime soon.

**Comment by erichelgeson** [comment]
It did! :)
